"""
Generates the Wi$h Li$t Test Report Excel file.
Run from project root: python docs/generate_test_report.py
"""

import openpyxl
from openpyxl.styles import (
    Font, PatternFill, Alignment, Border, Side, GradientFill
)
from openpyxl.utils import get_column_letter

# ---------------------------------------------------------------------------
# Test data — each entry maps to one test case
# Format: (module, class, test_name, steps, expected, tester, type)
# ---------------------------------------------------------------------------

TESTS = [
    # ── Category API ──────────────────────────────────────────────────────
    ("test_category_api", "TestListCategoriesEndpoint", "test_returns_200_when_categories_exist",
     "Send GET /users/{user_id}/list-categories with a valid UUID; mock service to return 4 categories.",
     "HTTP 200 OK", "Akif Emre Reis", "API"),
    ("test_category_api", "TestListCategoriesEndpoint", "test_response_is_list",
     "Send GET /users/{user_id}/list-categories; inspect response body type.",
     "Response body is a JSON array", "Akif Emre Reis", "API"),
    ("test_category_api", "TestListCategoriesEndpoint", "test_returns_correct_number_of_categories",
     "Send GET /users/{user_id}/list-categories; mock service to return 4 categories; count items.",
     "Response contains exactly 4 items", "Akif Emre Reis", "API"),
    ("test_category_api", "TestListCategoriesEndpoint", "test_initializes_defaults_when_list_is_empty",
     "Mock list_user_categories to return []; verify initialize_default_categories is called.",
     "initialize_default_categories called once", "Akif Emre Reis", "API"),
    ("test_category_api", "TestListCategoriesEndpoint", "test_does_not_initialize_when_categories_exist",
     "Mock list_user_categories to return 4 categories; verify initialize_default_categories is NOT called.",
     "initialize_default_categories not called", "Akif Emre Reis", "API"),
    ("test_category_api", "TestListCategoriesEndpoint", "test_invalid_user_id_returns_422",
     "Send GET /users/not-a-uuid/list-categories with a non-UUID user_id.",
     "HTTP 422 Unprocessable Entity", "Akif Emre Reis", "API"),
    ("test_category_api", "TestListCategoriesEndpoint", "test_category_has_name_field",
     "Send GET /users/{user_id}/list-categories; inspect first item in response for 'name' key.",
     "Response item contains 'name' field", "Akif Emre Reis", "API"),
    ("test_category_api", "TestListCategoriesEndpoint", "test_category_has_id_field",
     "Send GET /users/{user_id}/list-categories; inspect first item in response for 'id' key.",
     "Response item contains 'id' field", "Akif Emre Reis", "API"),
    ("test_category_api", "TestInitializeCategoriesEndpoint", "test_returns_200_on_success",
     "Send POST /users/{user_id}/initialize-categories; mock service to return 4 default categories.",
     "HTTP 200 OK", "Akif Emre Reis", "API"),
    ("test_category_api", "TestInitializeCategoriesEndpoint", "test_response_contains_four_categories",
     "Send POST /users/{user_id}/initialize-categories; count returned categories.",
     "Response is list of 4 categories", "Akif Emre Reis", "API"),
    ("test_category_api", "TestInitializeCategoriesEndpoint", "test_response_includes_technology",
     "Send POST /users/{user_id}/initialize-categories; check that 'Technology' is in returned names.",
     "'Technology' present in response", "Akif Emre Reis", "API"),
    ("test_category_api", "TestInitializeCategoriesEndpoint", "test_invalid_user_id_returns_422",
     "Send POST /users/bad-uuid/initialize-categories with non-UUID.",
     "HTTP 422 Unprocessable Entity", "Akif Emre Reis", "API"),
    ("test_category_api", "TestInitializeCategoriesEndpoint", "test_service_called_with_correct_user_id",
     "Send POST /users/{uid}/initialize-categories; assert service receives exact same UUID.",
     "Service called with matching user_id", "Akif Emre Reis", "API"),
    ("test_category_api", "TestAddNewCategoryEndpoint", "test_returns_200_on_valid_request",
     "POST /users/{user_id}/add-new-category with {name, category_type}; mock service.",
     "HTTP 200 OK", "Akif Emre Reis", "API"),
    ("test_category_api", "TestAddNewCategoryEndpoint", "test_response_contains_category_name",
     "POST add-new-category with name='Sports'; assert response name equals 'Sports'.",
     "Response 'name' == 'Sports'", "Akif Emre Reis", "API"),
    ("test_category_api", "TestAddNewCategoryEndpoint", "test_missing_name_returns_422",
     "POST add-new-category with body missing 'name' field.",
     "HTTP 422 Unprocessable Entity", "Akif Emre Reis", "API"),
    ("test_category_api", "TestAddNewCategoryEndpoint", "test_category_type_defaults_to_custom_when_omitted",
     "POST add-new-category with only {name}; category_type should default to CUSTOM.",
     "HTTP 200 OK (category_type defaults to 'CUSTOM')", "Akif Emre Reis", "API"),
    ("test_category_api", "TestAddNewCategoryEndpoint", "test_empty_body_returns_422",
     "POST add-new-category with empty JSON body {}.",
     "HTTP 422 Unprocessable Entity", "Akif Emre Reis", "API"),
    ("test_category_api", "TestAddNewCategoryEndpoint", "test_invalid_user_id_returns_422",
     "POST /users/not-a-uuid/add-new-category with non-UUID user_id.",
     "HTTP 422 Unprocessable Entity", "Akif Emre Reis", "API"),

    # ── Category Factory ──────────────────────────────────────────────────
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_returns_category_instance",
     "Call CategoryFactory.create_predefined(user_id, TECHNOLOGY); check returned type.",
     "Returns Category instance", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_name_equals_enum_value",
     "Call create_predefined with COSMETICS; check name field.",
     "name == 'Cosmetics'", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_clothing_name",
     "Call create_predefined with CLOTHING; check name field.",
     "name == 'Clothing'", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_kitchen_name",
     "Call create_predefined with KITCHEN; check name field.",
     "name == 'Kitchen Utensils'", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_category_type_equals_enum_name",
     "Call create_predefined with CLOTHING; check category_type field.",
     "category_type == 'CLOTHING'", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_user_id_is_set_correctly",
     "Call create_predefined with a known UUID; verify user_id on result.",
     "user_id matches input UUID", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_id_is_none_before_save",
     "Call create_predefined; verify id field is None (not yet persisted).",
     "id == None", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_different_user_ids_produce_different_categories",
     "Call create_predefined twice with different UUIDs; compare user_id fields.",
     "user_id values differ", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_all_predefined_names_are_correct[Cosmetics-Cosmetics]",
     "Parametrized: COSMETICS → name should equal 'Cosmetics'.",
     "name == 'Cosmetics'", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_all_predefined_names_are_correct[Clothing-Clothing]",
     "Parametrized: CLOTHING → name should equal 'Clothing'.",
     "name == 'Clothing'", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_all_predefined_names_are_correct[Technology-Technology]",
     "Parametrized: TECHNOLOGY → name should equal 'Technology'.",
     "name == 'Technology'", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_all_predefined_names_are_correct[Kitchen Utensils-Kitchen Utensils]",
     "Parametrized: KITCHEN → name should equal 'Kitchen Utensils'.",
     "name == 'Kitchen Utensils'", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_all_predefined_have_no_id[Cosmetics]",
     "Parametrized: create_predefined(COSMETICS) → id must be None.",
     "id == None", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_all_predefined_have_no_id[Clothing]",
     "Parametrized: create_predefined(CLOTHING) → id must be None.",
     "id == None", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_all_predefined_have_no_id[Technology]",
     "Parametrized: create_predefined(TECHNOLOGY) → id must be None.",
     "id == None", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryPredefined", "test_all_predefined_have_no_id[Kitchen Utensils]",
     "Parametrized: create_predefined(KITCHEN) → id must be None.",
     "id == None", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryCustom", "test_returns_category_instance",
     "Call create_custom(user_id, CategoryCustom('Books','BOOKS')); check type.",
     "Returns Category instance", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryCustom", "test_name_is_preserved",
     "Call create_custom with name='My Books'; check result name.",
     "name == 'My Books'", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryCustom", "test_category_type_is_preserved",
     "Call create_custom with category_type='SPORTS'; check result.",
     "category_type == 'SPORTS'", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryCustom", "test_user_id_is_set_correctly",
     "Call create_custom with known UUID; verify user_id on result.",
     "user_id matches input UUID", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryCustom", "test_id_is_none_before_save",
     "Call create_custom; verify id is None.",
     "id == None", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryCustom", "test_name_with_spaces_preserved",
     "Call create_custom with name='Home Decor'; check name includes space.",
     "name == 'Home Decor'", "Elif Serra Öncü", "Unit"),
    ("test_category_factory", "TestCategoryFactoryCustom", "test_different_users_same_custom_name",
     "Call create_custom twice with different user IDs same name; compare user_ids.",
     "user_ids differ, names equal", "Elif Serra Öncü", "Unit"),

    # ── Category Service ──────────────────────────────────────────────────
    ("test_category_service", "TestInitializeDefaultCategories", "test_creates_one_category_per_predefined_enum",
     "Mock repository.save; call initialize_default_categories; count returned items.",
     "Returns len(PredefinedCategory) items", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestInitializeDefaultCategories", "test_repository_save_called_four_times",
     "Mock repository; call initialize_default_categories; assert save called 4 times.",
     "repository.save call_count == 4", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestInitializeDefaultCategories", "test_returns_list_of_categories",
     "Mock save; call initialize_default_categories; verify return is list of Category.",
     "Returns list[Category]", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestInitializeDefaultCategories", "test_saved_categories_have_ids",
     "Mock save to return Category with id; assert all results have non-None id.",
     "All categories have id != None", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestInitializeDefaultCategories", "test_category_names_match_predefined_values",
     "Mock save; collect names from result; compare to PredefinedCategory values.",
     "Names == {Cosmetics, Clothing, Technology, Kitchen Utensils}", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestInitializeDefaultCategories", "test_all_categories_belong_to_correct_user",
     "Mock save; call initialize; assert all returned categories have correct user_id.",
     "All user_id == input user_id", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestListUserCategories", "test_delegates_to_repository_find_by_user",
     "Mock find_by_user; call list_user_categories; assert find_by_user called with user_id.",
     "find_by_user called once with correct user_id", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestListUserCategories", "test_returns_list_from_repository",
     "Mock find_by_user to return list; verify same list returned.",
     "Returns same list as repository", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestListUserCategories", "test_returns_empty_list_when_no_categories",
     "Mock find_by_user to return []; verify service returns [].",
     "Returns empty list", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestListUserCategories", "test_does_not_call_save",
     "Mock repository; call list_user_categories; assert save was not called.",
     "save not called", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestCreateNewCategory", "test_calls_repository_save",
     "Mock save; call create_new_category; assert save called once.",
     "repository.save called once", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestCreateNewCategory", "test_saved_category_has_correct_name",
     "Mock save to return Category('Sports'); assert result name is 'Sports'.",
     "result.name == 'Sports'", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestCreateNewCategory", "test_returns_saved_category",
     "Mock save with expected Category; assert returned object is same.",
     "Returns same object as repository.save", "Elif Serra Öncü", "Unit"),
    ("test_category_service", "TestCreateNewCategory", "test_saved_category_has_user_id",
     "Mock save using side_effect; verify saved category carries user_id.",
     "result.user_id == input user_id", "Elif Serra Öncü", "Unit"),

    # ── Hepsiburada Scraper ───────────────────────────────────────────────
    ("test_hepsiburada_scraper", "TestExtractJsonldProduct", "test_finds_product_in_graph_array",
     "Parse HTML with JSON-LD @graph array containing a Product; call _extract_jsonld_product.",
     "Returns product dict with name", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractJsonldProduct", "test_finds_direct_product_type",
     "Parse HTML with JSON-LD @type=Product directly; call _extract_jsonld_product.",
     "Returns product dict", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractJsonldProduct", "test_returns_none_when_no_product_found",
     "Parse HTML with no Product JSON-LD; call _extract_jsonld_product.",
     "Returns None", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractJsonldProduct", "test_returns_none_on_empty_page",
     "Parse minimal HTML with no scripts; call _extract_jsonld_product.",
     "Returns None", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractJsonldProduct", "test_finds_product_in_list_format",
     "Parse HTML with JSON-LD as array of objects; call _extract_jsonld_product.",
     "Returns product dict", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractPrice", "test_extracts_price_from_offers_dict",
     "Call _extract_price with offers={price:'1299.99'}.",
     "Returns 1299.99", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractPrice", "test_handles_comma_as_decimal_separator",
     "Call _extract_price with price='37999,00' (Turkish format).",
     "Returns 37999.00", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractPrice", "test_extracts_price_from_offers_list",
     "Call _extract_price with offers as list.",
     "Returns 599.00", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractPrice", "test_returns_none_when_price_missing",
     "Call _extract_price with empty offers dict.",
     "Returns None", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractPrice", "test_returns_none_when_no_offers",
     "Call _extract_price with empty product dict.",
     "Returns None", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractPrice", "test_integer_price_string",
     "Call _extract_price with price='5000'.",
     "Returns 5000.0", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractCurrency", "test_returns_currency_from_offers",
     "Call _extract_currency with priceCurrency='USD'.",
     "Returns 'USD'", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractCurrency", "test_defaults_to_try",
     "Call _extract_currency with empty offers.",
     "Returns 'TRY'", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractCurrency", "test_defaults_to_try_when_no_offers",
     "Call _extract_currency with empty product dict.",
     "Returns 'TRY'", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractCurrency", "test_currency_from_list_offers",
     "Call _extract_currency with offers as list containing priceCurrency='EUR'.",
     "Returns 'EUR'", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractImage", "test_extracts_first_image_from_list",
     "Call _extract_image with image=[url1, url2].",
     "Returns url1", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractImage", "test_extracts_image_string",
     "Call _extract_image with image='url'.",
     "Returns 'url'", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractImage", "test_returns_none_when_no_image",
     "Call _extract_image with empty dict.",
     "Returns None", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractImage", "test_returns_none_for_empty_list",
     "Call _extract_image with image=[].",
     "Returns None", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractProductData", "test_raises_scraping_error_on_http_failure",
     "Mock curl_requests.get to raise Exception; call extract_product_data.",
     "Raises ScrapingError", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractProductData", "test_raises_scraping_error_when_no_jsonld",
     "Mock HTTP response with HTML containing no JSON-LD; call extract_product_data.",
     "Raises ScrapingError", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractProductData", "test_returns_scraped_product_data",
     "Mock HTTP response with valid JSON-LD; call extract_product_data.",
     "Returns ScrapedProductData with title and price", "Akif Emre Reis", "Unit"),
    ("test_hepsiburada_scraper", "TestExtractProductData", "test_scraped_data_contains_image_url",
     "Mock HTTP response with image in JSON-LD; assert image_url in result.",
     "result.image_url == expected CDN URL", "Akif Emre Reis", "Unit"),

    # ── LLM Scraper ───────────────────────────────────────────────────────
    ("test_llm_scraper", "TestLLMScraperParsePrice", "test_parses_float_directly",
     "Call LLMScraper._parse_price(1299.99).",
     "Returns 1299.99", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperParsePrice", "test_parses_integer",
     "Call _parse_price(5000).",
     "Returns 5000.0", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperParsePrice", "test_parses_string_number",
     "Call _parse_price('2499.99').",
     "Returns 2499.99", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperParsePrice", "test_removes_comma_thousand_separator",
     "Call _parse_price('1,299.00') — US thousand-separator format.",
     "Returns 1299.00", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperParsePrice", "test_returns_none_for_none",
     "Call _parse_price(None).",
     "Returns None", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperParsePrice", "test_returns_none_for_invalid_string",
     "Call _parse_price('not-a-price').",
     "Returns None", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperParsePrice", "test_returns_none_for_empty_string",
     "Call _parse_price('').",
     "Returns None", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperParsePrice", "test_parses_zero",
     "Call _parse_price(0).",
     "Returns 0.0", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperParsePrice", "test_parses_string_with_spaces",
     "Call _parse_price('  999.00  ') with leading/trailing spaces.",
     "Returns 999.0", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperExtractProductData", "test_returns_scraped_product_data",
     "Mock HTTP + Groq returning valid JSON; call extract_product_data.",
     "Returns ScrapedProductData", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperExtractProductData", "test_price_is_parsed_correctly",
     "Mock Groq returning price=25000.0; verify result.current_price.",
     "current_price == 25000.0", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperExtractProductData", "test_currency_is_set_from_llm_response",
     "Mock Groq returning currency='USD'; verify result.currency.",
     "currency == 'USD'", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperExtractProductData", "test_source_domain_is_extracted_from_url",
     "Call extract_product_data with ciceksepeti.com URL; verify source_domain.",
     "source_domain == 'www.ciceksepeti.com'", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperExtractProductData", "test_raises_scraping_error_on_http_failure",
     "Mock HTTP to raise exception; call extract_product_data.",
     "Raises ScrapingError", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperExtractProductData", "test_raises_scraping_error_when_llm_returns_invalid_json",
     "Mock Groq to return non-JSON text; call extract_product_data.",
     "Raises ScrapingError", "Alaaddin Gürsoy", "Unit"),
    ("test_llm_scraper", "TestLLMScraperExtractProductData", "test_defaults_unknown_product_title_when_missing",
     "Mock Groq returning JSON without 'title'; verify default title.",
     "title == 'Unknown Product'", "Alaaddin Gürsoy", "Unit"),

    # ── New Scrapers ──────────────────────────────────────────────────────
    ("test_new_scrapers", "TestTrendyolScraperParsers", "test_extract_price_from_discounted_span",
     "Parse HTML with <span class='discounted'>1.299,90 TL</span>; call _extract_price.",
     "Returns 1299.90", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestTrendyolScraperParsers", "test_extract_price_returns_none_when_missing",
     "Parse HTML with no discounted span; call _extract_price.",
     "Returns None", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestTrendyolScraperParsers", "test_extract_title_from_h1",
     "Parse HTML with <h1 class='product-title'>; call _extract_title.",
     "Title contains brand name", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestTrendyolScraperParsers", "test_extract_title_returns_none_when_missing",
     "Parse empty HTML; call _extract_title.",
     "Returns None", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestTrendyolScraperParsers", "test_extract_image_returns_none_when_missing",
     "Parse empty HTML; call _extract_image.",
     "Returns None", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestTrendyolScraperParsers", "test_extract_raises_scraping_error_on_http_failure",
     "Mock curl_requests.get to raise Exception; call extract_product_data.",
     "Raises ScrapingError", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestTrendyolScraperParsers", "test_extract_returns_scraped_data",
     "Mock HTTP response with product HTML; call extract_product_data.",
     "Returns ScrapedProductData with source_domain='trendyol.com'", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestAmazonScraperParsers", "test_extract_price_from_price_whole",
     "Parse HTML with <span class='a-price-whole'>4.599</span>; call _extract_price.",
     "Returns 4599.0", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestAmazonScraperParsers", "test_extract_price_returns_none_when_missing",
     "Parse empty HTML; call _extract_price.",
     "Returns None", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestAmazonScraperParsers", "test_extract_title_from_product_title",
     "Parse HTML with <span id='productTitle'>; call _extract_title.",
     "Returns stripped title string", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestAmazonScraperParsers", "test_extract_title_returns_none_when_missing",
     "Parse empty HTML; call _extract_title.",
     "Returns None", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestAmazonScraperParsers", "test_extract_image_from_landing_image",
     "Parse HTML with landingImage and data-old-hires; call _extract_image.",
     "Returns data-old-hires URL", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestAmazonScraperParsers", "test_extract_image_falls_back_to_src",
     "Parse HTML with landingImage without data-old-hires; call _extract_image.",
     "Returns src attribute", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestAmazonScraperParsers", "test_extract_image_returns_none_when_missing",
     "Parse empty HTML; call _extract_image.",
     "Returns None", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestAmazonScraperParsers", "test_extract_raises_on_http_failure",
     "Mock HTTP to raise Timeout; call extract_product_data.",
     "Raises ScrapingError", "Alaaddin Gürsoy", "Unit"),
    ("test_new_scrapers", "TestBoynerScraperParsers", "test_extract_price_removes_tl_suffix",
     "Parse HTML with Boyner price tag containing 'TL'; call _extract_price.",
     "Returns 2499.00", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestBoynerScraperParsers", "test_extract_price_returns_none_when_missing",
     "Parse empty HTML; call _extract_price.",
     "Returns None", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestBoynerScraperParsers", "test_extract_title_combines_brand_and_name",
     "Parse HTML with brand tag and name tag; call _extract_title.",
     "Title contains both brand and product name", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestBoynerScraperParsers", "test_extract_title_returns_none_when_missing",
     "Parse empty HTML; call _extract_title.",
     "Returns None", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestBoynerScraperParsers", "test_extract_image_skips_data_urls",
     "Parse HTML with data:image placeholder then real CDN URL; call _extract_image.",
     "Returns CDN URL, not data URI", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestBoynerScraperParsers", "test_extract_image_returns_none_when_only_placeholder",
     "Parse HTML with only data:image URLs; call _extract_image.",
     "Returns None", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestBoynerScraperParsers", "test_extract_raises_on_http_failure",
     "Mock HTTP to raise Network error; call extract_product_data.",
     "Raises ScrapingError", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestMediaMarktScraperParsers", "test_extract_price_removes_currency_symbols",
     "Parse HTML with ₺12.999 in branded-price tag; call _extract_price.",
     "Returns 12999.0", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestMediaMarktScraperParsers", "test_extract_price_returns_none_when_missing",
     "Parse empty HTML; call _extract_price.",
     "Returns None", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestMediaMarktScraperParsers", "test_extract_title_from_h1",
     "Parse HTML with <h1 class='sc-*'>; call _extract_title.",
     "Returns title text", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestMediaMarktScraperParsers", "test_extract_title_returns_none_when_missing",
     "Parse empty HTML; call _extract_title.",
     "Returns None", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestMediaMarktScraperParsers", "test_extract_image_skips_data_urls",
     "Parse HTML with data:image placeholder then CDN src; call _extract_image.",
     "Returns CDN URL", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestMediaMarktScraperParsers", "test_extract_image_returns_none_when_missing",
     "Parse empty HTML; call _extract_image.",
     "Returns None", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestMediaMarktScraperParsers", "test_extract_raises_on_http_failure",
     "Mock HTTP to raise SSL error; call extract_product_data.",
     "Raises ScrapingError", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestTeknosaScraper", "test_extract_price_from_visible_pi_input",
     "Parse HTML with <input id='visiblePi' value='8.999,00'/>; call _extract_price.",
     "Returns 8999.00", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestTeknosaScraper", "test_extract_price_from_prc_span_fallback",
     "Parse HTML with <span class='prc'>5.499,99 TL</span>; call _extract_price.",
     "Returns 5499.99", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestTeknosaScraper", "test_extract_price_returns_none_when_missing",
     "Parse empty HTML; call _extract_price.",
     "Returns None", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestTeknosaScraper", "test_extract_title_combines_brand_and_name",
     "Parse HTML with brand link and replaceName span; call _extract_title.",
     "Title contains both brand and name", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestTeknosaScraper", "test_extract_title_returns_none_when_both_missing",
     "Parse empty HTML; call _extract_title.",
     "Returns None", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestTeknosaScraper", "test_extract_image_from_swiper_zoom",
     "Parse HTML with swiper-slide data-zoom URL; call _extract_image.",
     "Returns URL with /600/600 substituted for /1200/1200", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestTeknosaScraper", "test_extract_image_returns_none_when_missing",
     "Parse empty HTML; call _extract_image.",
     "Returns None", "Gizem Elif Bayar", "Unit"),
    ("test_new_scrapers", "TestTeknosaScraper", "test_extract_raises_on_http_failure",
     "Mock HTTP to raise Timeout; call extract_product_data.",
     "Raises ScrapingError", "Gizem Elif Bayar", "Unit"),

    # ── Product API ───────────────────────────────────────────────────────
    ("test_product_api", "TestAddProductEndpoint", "test_returns_200_on_valid_product",
     "POST /users/{id}/products with valid ProductCreate payload; mock service.",
     "HTTP 200 OK", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestAddProductEndpoint", "test_response_contains_product_name",
     "POST add product; assert response JSON contains 'name' field.",
     "response.name == 'Test Laptop'", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestAddProductEndpoint", "test_response_contains_user_id",
     "POST add product; assert response JSON contains 'user_id' field.",
     "Response has 'user_id'", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestAddProductEndpoint", "test_missing_name_returns_422",
     "POST add product without 'name' field in payload.",
     "HTTP 422 Unprocessable Entity", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestAddProductEndpoint", "test_invalid_user_id_returns_422",
     "POST /users/not-a-uuid/products.",
     "HTTP 422 Unprocessable Entity", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestAddProductEndpoint", "test_service_returns_none_gives_error_response",
     "Mock service.add_product to return None; verify error response (400 or 500).",
     "HTTP 400 or 500", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestAddProductEndpoint", "test_service_exception_returns_500",
     "Mock service.add_product to raise Exception('DB error').",
     "HTTP 500 Internal Server Error", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestScrapeAndAddProductEndpoint", "test_returns_200_on_valid_scrape",
     "POST /users/{id}/products/scrape with valid URL payload; mock service.",
     "HTTP 200 OK", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestScrapeAndAddProductEndpoint", "test_response_has_product_id",
     "POST scrape; verify response contains 'id' field.",
     "Response has 'id'", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestScrapeAndAddProductEndpoint", "test_unsupported_platform_returns_400",
     "Mock service to raise UnsupportedPlatformError; POST scrape endpoint.",
     "HTTP 400 Bad Request", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestScrapeAndAddProductEndpoint", "test_scraping_error_returns_502",
     "Mock service to raise ScrapingError; POST scrape endpoint.",
     "HTTP 502 Bad Gateway", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestScrapeAndAddProductEndpoint", "test_missing_url_returns_422",
     "POST scrape without 'url' field.",
     "HTTP 422 Unprocessable Entity", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestScrapeAndAddProductEndpoint", "test_invalid_user_id_returns_422",
     "POST /users/not-a-uuid/products/scrape.",
     "HTTP 422 Unprocessable Entity", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestGetUserProductsEndpoint", "test_returns_200",
     "GET /users/{id}/products; mock service to return list.",
     "HTTP 200 OK", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestGetUserProductsEndpoint", "test_returns_list",
     "GET /users/{id}/products; assert response is JSON array.",
     "Response is list", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestGetUserProductsEndpoint", "test_returns_correct_count",
     "GET /users/{id}/products; mock 3 products; assert count.",
     "Response length == 3", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestGetUserProductsEndpoint", "test_invalid_user_id_returns_422",
     "GET /users/not-a-uuid/products.",
     "HTTP 422 Unprocessable Entity", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestGetUserProductsEndpoint", "test_service_exception_returns_500",
     "Mock service to raise Exception; GET products.",
     "HTTP 500 Internal Server Error", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestUpdateProductEndpoint", "test_returns_200_on_valid_update",
     "PUT /products/{id} with valid ProductUpdate; mock service.",
     "HTTP 200 OK", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestUpdateProductEndpoint", "test_response_contains_id",
     "PUT /products/{id}; assert response has 'id' field.",
     "Response has 'id'", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestUpdateProductEndpoint", "test_service_returns_none_gives_404",
     "Mock service.update_product_details to return None.",
     "HTTP 404 Not Found", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestUpdateProductEndpoint", "test_invalid_product_id_returns_422",
     "PUT /products/not-a-uuid.",
     "HTTP 422 Unprocessable Entity", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestUpdateProductEndpoint", "test_update_purchase_state",
     "PUT /products/{id} with purchase_state='purchased'; mock service.",
     "HTTP 200 OK", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestDeleteProductEndpoint", "test_returns_200_on_success",
     "DELETE /products/{id}; mock service.remove_product.",
     "HTTP 200 OK", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestDeleteProductEndpoint", "test_response_contains_detail_message",
     "DELETE /products/{id}; assert response has 'detail' field.",
     "Response has 'detail' key", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestDeleteProductEndpoint", "test_invalid_product_id_returns_422",
     "DELETE /products/not-a-uuid.",
     "HTTP 422 Unprocessable Entity", "Alaaddin Gürsoy", "API"),
    ("test_product_api", "TestDeleteProductEndpoint", "test_service_exception_returns_500",
     "Mock service.remove_product to raise Exception.",
     "HTTP 500 Internal Server Error", "Alaaddin Gürsoy", "API"),

    # ── Product Service ───────────────────────────────────────────────────
    ("test_product_service", "TestAddProduct", "test_delegates_to_repository_create_product",
     "Mock repository; call service.add_product; assert create_product called.",
     "repository.create_product called once", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestAddProduct", "test_returns_created_product",
     "Mock repository to return product; assert same object returned.",
     "Returns same object as repository", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestAddProduct", "test_passes_user_id_to_repository",
     "Call add_product with specific UUID; assert repository receives same UUID.",
     "repository called with matching user_id", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestAddProductFromUrl", "test_calls_scraper_factory_with_url",
     "Patch ScraperFactory.create_scraper; call add_product_from_url; assert factory called with URL.",
     "ScraperFactory.create_scraper called with URL string", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestAddProductFromUrl", "test_strategy_extract_is_called",
     "Mock strategy; call add_product_from_url; assert extract_product_data called.",
     "strategy.extract_product_data called once", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestAddProductFromUrl", "test_product_create_uses_scraped_title",
     "Mock scraped data with title='Scraped Title'; assert ProductCreate.name == 'Scraped Title'.",
     "ProductCreate.name == 'Scraped Title'", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestAddProductFromUrl", "test_product_create_uses_scraped_price",
     "Mock scraped data with current_price=29999.0; assert ProductCreate.current_price matches.",
     "ProductCreate.current_price == 29999.0", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestAddProductFromUrl", "test_product_create_uses_scraped_image",
     "Mock scraped data with image_url; assert ProductCreate.image_url matches.",
     "ProductCreate.image_url == scraped image URL", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestAddProductFromUrl", "test_unsupported_platform_error_propagates",
     "Patch factory to raise UnsupportedPlatformError; call add_product_from_url.",
     "Raises UnsupportedPlatformError", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestAddProductFromUrl", "test_scraping_error_propagates",
     "Mock strategy.extract_product_data to raise ScrapingError.",
     "Raises ScrapingError", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestGetUserProducts", "test_delegates_to_repository",
     "Mock get_products_by_user; call get_user_products; assert called with user_id.",
     "get_products_by_user called with correct user_id", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestGetUserProducts", "test_returns_products_list",
     "Mock repository to return list; assert same list returned.",
     "Returns repository's list", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestGetUserProducts", "test_returns_empty_list_when_no_products",
     "Mock repository to return []; verify empty list returned.",
     "Returns []", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestUpdateProductDetails", "test_delegates_to_repository",
     "Mock update_product; call update_product_details; assert called with correct args.",
     "repository.update_product called with (product_id, update_data)", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestUpdateProductDetails", "test_returns_updated_product",
     "Mock repository to return updated product; assert same object returned.",
     "Returns same object as repository", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestRemoveProduct", "test_delegates_to_repository",
     "Call remove_product with product_id; assert delete_product called.",
     "repository.delete_product called with product_id", "Gizem Elif Bayar", "Unit"),
    ("test_product_service", "TestRemoveProduct", "test_does_not_call_other_methods",
     "Call remove_product; assert create_product and get_products_by_user not called.",
     "No other repository methods called", "Gizem Elif Bayar", "Unit"),

    # ── Scheduler ────────────────────────────────────────────────────────
    ("test_scheduler", "TestCheckPricesFunction", "test_fetches_auto_track_products",
     "Patch supabase; call check_prices(); assert .eq('auto_track', True) called.",
     "Supabase queried with auto_track=True filter", "Gizem Elif Bayar", "Unit"),
    ("test_scheduler", "TestCheckPricesFunction", "test_skips_products_without_url",
     "Provide product with url=None; assert ScraperFactory not called.",
     "ScraperFactory.create_scraper not called", "Gizem Elif Bayar", "Unit"),
    ("test_scheduler", "TestCheckPricesFunction", "test_calls_scraper_factory_for_each_product",
     "Provide 3 products; assert ScraperFactory called 3 times.",
     "ScraperFactory called 3 times", "Gizem Elif Bayar", "Unit"),
    ("test_scheduler", "TestCheckPricesFunction", "test_saves_new_price_to_price_history",
     "Mock scraper returning price=899.0; assert price_history insert called with price=899.0.",
     "price_history.insert called with price=899.0", "Gizem Elif Bayar", "Unit"),
    ("test_scheduler", "TestCheckPricesFunction", "test_updates_current_price_in_products_table",
     "Mock scraper returning price=850.0; assert products.update called with current_price=850.0.",
     "products.update called with {'current_price': 850.0}", "Gizem Elif Bayar", "Unit"),
    ("test_scheduler", "TestCheckPricesFunction", "test_skips_product_when_scraped_price_is_none",
     "Mock scraper returning current_price=None; assert update not called.",
     "No update call when price is None", "Gizem Elif Bayar", "Unit"),
    ("test_scheduler", "TestCheckPricesFunction", "test_continues_on_single_product_scraping_error",
     "First product scrape fails with ScrapingError; verify second product is still processed.",
     "ScraperFactory called twice (loop continues)", "Gizem Elif Bayar", "Unit"),
    ("test_scheduler", "TestCheckPricesFunction", "test_does_not_raise_when_supabase_fails",
     "Mock supabase.table to raise Exception; call check_prices(); no exception propagates.",
     "No exception raised", "Gizem Elif Bayar", "Unit"),
    ("test_scheduler", "TestStartScheduler", "test_scheduler_is_started",
     "Mock BackgroundScheduler; call start_scheduler(); assert .start() called.",
     "scheduler.start() called once", "Gizem Elif Bayar", "Unit"),
    ("test_scheduler", "TestStartScheduler", "test_scheduler_adds_check_prices_job",
     "Mock BackgroundScheduler; call start_scheduler(); assert add_job called with check_prices.",
     "add_job called with check_prices function", "Gizem Elif Bayar", "Unit"),

    # ── Scraper Factory ───────────────────────────────────────────────────
    ("test_scraper_factory", "TestScraperFactoryRegisteredPlatforms", "test_hepsiburada_url_returns_hepsiburada_scraper",
     "Call ScraperFactory.create_scraper with hepsiburada.com URL.",
     "Returns HepsiburadaScraper instance", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryRegisteredPlatforms", "test_trendyol_url_returns_trendyol_scraper",
     "Call create_scraper with trendyol.com URL.",
     "Returns TrendyolScraper instance", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryRegisteredPlatforms", "test_amazon_url_returns_amazon_scraper",
     "Call create_scraper with amazon.com.tr URL.",
     "Returns AmazonScraper instance", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryRegisteredPlatforms", "test_boyner_url_returns_boyner_scraper",
     "Call create_scraper with boyner.com.tr URL.",
     "Returns BoynerScraper instance", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryRegisteredPlatforms", "test_mediamarkt_url_returns_mediamarkt_scraper",
     "Call create_scraper with mediamarkt.com.tr URL.",
     "Returns MediaMarktScraper instance", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryRegisteredPlatforms", "test_teknosa_url_returns_teknosa_scraper",
     "Call create_scraper with teknosa.com URL.",
     "Returns TeknosaScraper instance", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryLLMFallback", "test_unknown_domain_falls_back_to_llm_scraper",
     "Call create_scraper with n11.com URL (not registered).",
     "Returns LLMScraper instance", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryLLMFallback", "test_unsupported_platform_returns_llm_not_raises",
     "Call create_scraper with ciceksepeti.com URL; no exception expected.",
     "Returns LLMScraper (no exception)", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryLLMFallback", "test_completely_unknown_site_returns_llm",
     "Call create_scraper with randomshop.com URL.",
     "Returns LLMScraper instance", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryInterface", "test_all_registered_scrapers_implement_strategy",
     "Call create_scraper for all 6 registered domains; check each is ScraperStrategy subclass.",
     "All scrapers implement ScraperStrategy", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryInterface", "test_llm_fallback_also_implements_strategy",
     "Call create_scraper with unknown domain; check LLMScraper is ScraperStrategy subclass.",
     "LLMScraper implements ScraperStrategy", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryInterface", "test_each_call_returns_new_instance",
     "Call create_scraper twice with same URL; assert two different instances.",
     "s1 is not s2", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryInterface", "test_hepsiburada_without_www",
     "Call create_scraper with https://hepsiburada.com (no www).",
     "Returns HepsiburadaScraper", "Akif Emre Reis", "Unit"),
    ("test_scraper_factory", "TestScraperFactoryInterface", "test_trendyol_without_www",
     "Call create_scraper with https://trendyol.com (no www).",
     "Returns TrendyolScraper", "Akif Emre Reis", "Unit"),

    # ── User API ──────────────────────────────────────────────────────────
    ("test_user_api", "TestCreateUserEndpoint", "test_returns_200_on_valid_request",
     "POST /users with {first_name, last_name, email}; mock service.",
     "HTTP 200 OK", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestCreateUserEndpoint", "test_response_contains_email",
     "POST /users; assert response JSON has matching email.",
     "response.email == input email", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestCreateUserEndpoint", "test_missing_first_name_returns_422",
     "POST /users without first_name field.",
     "HTTP 422 Unprocessable Entity", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestCreateUserEndpoint", "test_missing_last_name_returns_422",
     "POST /users without last_name field.",
     "HTTP 422 Unprocessable Entity", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestCreateUserEndpoint", "test_missing_email_returns_422",
     "POST /users without email field.",
     "HTTP 422 Unprocessable Entity", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestCreateUserEndpoint", "test_empty_body_returns_422",
     "POST /users with empty JSON body {}.",
     "HTTP 422 Unprocessable Entity", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestCreateUserEndpoint", "test_service_called_with_correct_args",
     "POST /users with Elif/Çelik/elif@test.com; assert service.create_user called with matching args.",
     "Service called with first_name='Elif', last_name='Çelik', email='elif@test.com'", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestUserStatsEndpoint", "test_returns_200",
     "GET /users/{id}/stats; mock supabase returning empty products.",
     "HTTP 200 OK", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestUserStatsEndpoint", "test_response_has_required_fields",
     "GET /users/{id}/stats; assert response has tracked, purchased, total_savings, price_drops_today.",
     "All 4 required fields present", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestUserStatsEndpoint", "test_tracked_count_equals_product_count",
     "Mock 3 products; GET stats; assert tracked == 3.",
     "tracked == 3", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestUserStatsEndpoint", "test_purchased_count_filters_by_state",
     "Mock 2 purchased + 1 pending; GET stats; assert purchased == 2.",
     "purchased == 2", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestUserStatsEndpoint", "test_total_savings_calculated_for_price_drops",
     "Mock product with current=800, target=1000; GET stats; assert total_savings == 200.",
     "total_savings == 200.0", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestUserStatsEndpoint", "test_total_savings_zero_when_no_products",
     "Mock empty products list; GET stats; assert total_savings == 0.",
     "total_savings == 0.0", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestUserStatsEndpoint", "test_price_drops_today_counted_correctly",
     "Mock 2 price_history records for same product (price dropped); GET stats; assert price_drops_today == 1.",
     "price_drops_today == 1", "Elif Serra Öncü", "API"),
    ("test_user_api", "TestUserStatsEndpoint", "test_invalid_user_id_returns_422",
     "GET /users/not-a-uuid/stats.",
     "HTTP 422 Unprocessable Entity", "Elif Serra Öncü", "API"),

    # ── User Service ──────────────────────────────────────────────────────
    ("test_user_service", "TestCreateUser", "test_calls_repository_save",
     "Mock repository.save; call service.create_user; assert save called once.",
     "repository.save called once", "Elif Serra Öncü", "Unit"),
    ("test_user_service", "TestCreateUser", "test_passes_correct_first_name",
     "Call create_user('Zeynep', ...); assert save receives first_name='Zeynep'.",
     "saved_user.first_name == 'Zeynep'", "Elif Serra Öncü", "Unit"),
    ("test_user_service", "TestCreateUser", "test_passes_correct_last_name",
     "Call create_user with last_name='Yılmaz'; assert save receives correct last_name.",
     "saved_user.last_name == 'Yılmaz'", "Elif Serra Öncü", "Unit"),
    ("test_user_service", "TestCreateUser", "test_passes_correct_email",
     "Call create_user with email='can@example.com'; assert save receives same email.",
     "saved_user.email == 'can@example.com'", "Elif Serra Öncü", "Unit"),
    ("test_user_service", "TestCreateUser", "test_passes_user_create_schema_to_repo",
     "Call create_user; assert arg passed to save is UserCreate instance.",
     "isinstance(saved_user, UserCreate) == True", "Elif Serra Öncü", "Unit"),
    ("test_user_service", "TestCreateUser", "test_returns_saved_user",
     "Mock save to return UserRead; assert same object returned from service.",
     "Returns same object as repository.save", "Elif Serra Öncü", "Unit"),
    ("test_user_service", "TestCreateUser", "test_returns_user_with_id",
     "Mock save to return UserRead with UUID id; assert result.id is not None.",
     "result.id != None", "Elif Serra Öncü", "Unit"),
    ("test_user_service", "TestCreateUser", "test_different_emails_produce_different_save_calls",
     "Call create_user twice with different emails; assert save called twice with different emails.",
     "save called 2 times with distinct emails", "Elif Serra Öncü", "Unit"),
]

# ---------------------------------------------------------------------------
# Excel generation
# ---------------------------------------------------------------------------

def col_width(ws, col, width):
    ws.column_dimensions[get_column_letter(col)].width = width

def make_border(thin=True):
    s = Side(style="thin" if thin else "medium")
    return Border(left=s, right=s, top=s, bottom=s)

def build_report():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Test Report"

    # ── Palette ──────────────────────────────────────────────────────────
    HDR_BG   = "1F3864"   # dark navy
    HDR_FG   = "FFFFFF"
    PASS_BG  = "E2EFDA"   # light green
    API_BG   = "DDEEFF"   # light blue
    UNIT_BG  = "FFF2CC"   # light yellow
    ALT_BG   = "F5F5F5"   # off-white alternate
    BORDER   = make_border()

    # ── Column headers ────────────────────────────────────────────────────
    HEADERS = [
        "Test ID", "Test File", "Test Class", "Test Name",
        "Test Type", "Test Steps", "Expected Result", "Actual Result",
        "Tester", "Date", "Environment", "Status", "Log Reference", "Notes",
    ]
    widths   = [9, 22, 32, 52, 10, 55, 40, 40, 20, 13, 35, 9, 18, 30]

    # Title row
    ws.merge_cells("A1:N1")
    title_cell = ws["A1"]
    title_cell.value = "Wi$h Li$t – Test Report   |   223 tests   |   April 13, 2026"
    title_cell.font = Font(name="Calibri", bold=True, size=14, color=HDR_FG)
    title_cell.fill = PatternFill("solid", fgColor=HDR_BG)
    title_cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 28

    # Header row
    for col_idx, (hdr, w) in enumerate(zip(HEADERS, widths), start=1):
        cell = ws.cell(row=2, column=col_idx, value=hdr)
        cell.font = Font(name="Calibri", bold=True, size=10, color=HDR_FG)
        cell.fill = PatternFill("solid", fgColor=HDR_BG)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = BORDER
        col_width(ws, col_idx, w)
    ws.row_dimensions[2].height = 32

    # Freeze header
    ws.freeze_panes = "A3"

    # Data rows
    for row_idx, (module, cls, test_name, steps, expected, tester, ttype) in enumerate(TESTS, start=1):
        r = row_idx + 2   # row in sheet (1=title, 2=header)

        test_id = f"TC-{row_idx:03d}"
        actual  = expected           # all tests passed
        status  = "PASS"
        env     = "Python 3.13.5 | pytest 9.0.3 | FastAPI | Windows 11"
        log_ref = f"test_report.txt L{(row_idx - 1) * 1 + 8}"
        date    = "2026-04-13"
        notes   = ""

        row_data = [
            test_id, module, cls, test_name,
            ttype, steps, expected, actual,
            tester, date, env, status, log_ref, notes,
        ]

        # Alternating row background
        if ttype == "API":
            row_bg = API_BG
        elif row_idx % 2 == 0:
            row_bg = ALT_BG
        else:
            row_bg = "FFFFFF"

        for col_idx, val in enumerate(row_data, start=1):
            cell = ws.cell(row=r, column=col_idx, value=val)
            cell.font = Font(name="Calibri", size=9)
            cell.border = BORDER
            cell.alignment = Alignment(vertical="top", wrap_text=True)

            # Status cell gets green fill
            if col_idx == 12:
                cell.fill = PatternFill("solid", fgColor=PASS_BG)
                cell.font = Font(name="Calibri", size=9, bold=True, color="375623")
                cell.alignment = Alignment(horizontal="center", vertical="center")
            elif col_idx in (1, 5, 10, 12):
                cell.alignment = Alignment(horizontal="center", vertical="center")
                cell.fill = PatternFill("solid", fgColor=row_bg)
            else:
                cell.fill = PatternFill("solid", fgColor=row_bg)

        ws.row_dimensions[r].height = 38

    # Auto-filter
    ws.auto_filter.ref = f"A2:N{len(TESTS) + 2}"

    # ── Summary sheet ─────────────────────────────────────────────────────
    ws2 = wb.create_sheet("Summary")
    ws2.column_dimensions["A"].width = 30
    ws2.column_dimensions["B"].width = 16

    summary_data = [
        ("Wi$h Li$t – Test Summary", ""),
        ("", ""),
        ("Run Date", "2026-04-13"),
        ("Tester Team", "Akif, Alaaddin, Elif, Gizem"),
        ("Environment", "Python 3.13.5 / pytest 9.0.3 / FastAPI / Win11"),
        ("", ""),
        ("Total Tests", len(TESTS)),
        ("PASS", len(TESTS)),
        ("FAIL", 0),
        ("BLOCKED", 0),
        ("", ""),
        ("Unit Tests", sum(1 for t in TESTS if t[6] == "Unit")),
        ("API / Integration Tests", sum(1 for t in TESTS if t[6] == "API")),
        ("", ""),
        ("Testers", ""),
        ("  Akif Emre Reis",   sum(1 for t in TESTS if t[5] == "Akif Emre Reis")),
        ("  Alaaddin Gürsoy",  sum(1 for t in TESTS if t[5] == "Alaaddin Gürsoy")),
        ("  Elif Serra Öncü",  sum(1 for t in TESTS if t[5] == "Elif Serra Öncü")),
        ("  Gizem Elif Bayar", sum(1 for t in TESTS if t[5] == "Gizem Elif Bayar")),
    ]

    for r_idx, (label, val) in enumerate(summary_data, start=1):
        a = ws2.cell(row=r_idx, column=1, value=label)
        b = ws2.cell(row=r_idx, column=2, value=val)
        if r_idx == 1:
            a.font = Font(name="Calibri", bold=True, size=13, color=HDR_FG)
            ws2.merge_cells(f"A1:B1")
            a.fill = PatternFill("solid", fgColor=HDR_BG)
            a.alignment = Alignment(horizontal="center")
        else:
            a.font = Font(name="Calibri", size=10)
            b.font = Font(name="Calibri", size=10, bold=True)
        ws2.row_dimensions[r_idx].height = 18

    out_path = "docs/WishList_Test_Report.xlsx"
    wb.save(out_path)
    print(f"Report saved -> {out_path}")
    print(f"Total rows: {len(TESTS)}")

if __name__ == "__main__":
    build_report()
